---
title: Response to reviewers
author: ""
fontsize: 12pt
date: "Submission ID 217815520.R2"
output: monash::memo
# if you don't have the monash package install by:
# remotes::install_github("numbats/monash")
---

We thank the editor, associate editor and the reviewers for their feedback. Here is how we have made revisions to the manuscript to address each point. 


The editor says \textcolor{violet}{The reviews are in general quite favorable and suggest that, subject to the minor revisions that the paper would be suitable for publication as part of the special issue on reproducibility and responsible workflow.} 

Reviewer 3 also comments that \textcolor{violet}{Thank you for this revision.  My minor comments and corrections are all well addressed, and I particularly commend the authors for their changes to Section 3.4.  It was a great idea to create a Shiny app showing the exploratory process that lead to your choice of threshold; this feels far more justifiable and reproducible than reporting the final number alone.}


\section*{Major changes:}

The only comments on the pedagogical application of the data appear to come from the associate editor: \textcolor{violet}{While the data are interesting, the necessary details for a pedagogical application or case study are still largely missing. The manuscript reads more like a paper about the R package, something for a software journal. In my last review, I had missed that this was for a special issue, still I agree with the reviewer that the clear contributions to educators other than its use in class are plenty, but not fully described.}


\section*{Specific comments:}

\begin{description}
\item[Associate Editor:] \textcolor{violet}{The abstract promises a discussion of the process for cleaning data and exploratory analyses for longitudinal data. The latter is not provided, nor is a discussion about how that might be done in a class activity. This is a place for adding another clear contribution to educators. (Alternatively it can be deleted).}
\end{description}


\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 10, line 18) “these” is errant}
\end{description}

* Dewi to do

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 11, line 14) Providing one or two sentences about the use of pivot\_longer() would help readers gain insight and motivate clicking the link to the code.}
\end{description}

* Dewi to do

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 11, line 35) The sentence beginning “This information is provided” is missing at least one word.}
\end{description}

* Dewi to do

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 12, line 49) There is still the error stating that education should only increase. Certainly, you mean non-decreasing.}
\end{description}

* Dewi to do

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 13, line 24) I’m just checking that all Q... variables are correct. The formatting is inconsistent; e.g., Q3-8A versus Q1-3\_A}
\end{description}

* Yes it is correct, the formatting of all Q... variables uses the same format as downloaded data from the database. 

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 13, line 36) The sentence beginning “Our target variables” is missing at least one word.}
\end{description}

* Dewi to do

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 14, line 20) Why is 84 hours the cut-off? This seems to be an arbitrary choice.}
\end{description}

* It is assumed that people will not work more than 12 hours a day. Dewi to do. 


\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 15, line 3) The sentence beginning “For stwork variable” is missing at least one word.}
\end{description}

* Dewi to do

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 15, line 3)  It might be helpful for readers if you refer to variables as what they are and put the column title in parentheses.
}
\end{description}

* Dewi to do

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 15, line 15) Providing one or two sentences about the use of join() would help readers gain insight into what the authors are doing here.}
\end{description}

* Dewi to do

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 22, line 5) The default for rlm is huber weighting which never applies a weight of 0. You may have meant bisquare, but that change should be discussed.}
\end{description}

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 28, figure 7) This is a helpful graph, but perhaps making the barplot “position dodge” and the density plots overlapping with transparency would sell your point better. This graphic makes the point, but the suggestions I made may produce more compelling evidence.}
\end{description}

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 29, line 21) The sentence “The highest grade completed has some confusion” should be rewritten.}
\end{description}


\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 29, line 37) Naming the function would be helpful for readers interested in using it.}
\end{description}

* Dewi to do

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 31, line 9) Certainly you don’t mean to say that you’ve created data ”unsatisfactorily far from” the original.}
\end{description}

\begin{description}
\item[Associate Editor:] \textcolor{violet}{(page 32, line 18-30) Here you describe some modeling (see first note). Re-framing this as a possible activity could be helpful to the reader. As it is written now it sounds like a summary (the section title) of what was presented – instead you can make it a path forward for the readers.}
\end{description}














